// Generated by Selenium IDE
package carzone.com.selenium;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ContattaciTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void contattaci() {
    driver.get("http://localhost:8080/EcommerceApp/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.linkText("Contattaci")).click();
    driver.findElement(By.name("Name")).click();
    driver.findElement(By.name("Name")).click();
    driver.findElement(By.name("Name")).sendKeys("luca");
    driver.findElement(By.name("Email_Id")).click();
    driver.findElement(By.name("Email_Id")).sendKeys("luca@gmail.com");
    driver.findElement(By.name("Contact_Number")).click();
    driver.findElement(By.name("Contact_Number")).sendKeys("3333333");
    driver.findElement(By.name("Message")).click();
    driver.findElement(By.name("Message")).sendKeys("disponibile fiat 500?");
    driver.findElement(By.name("b1")).click();
  }
}
