// Generated by Selenium IDE
package carzone.com.selenium;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class OrdineAutoPagamentoConcessionariaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ordineAutoPagamentoConcessionaria() {
    driver.get("http://localhost:8080/EcommerceApp/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.cssSelector(".w3-bar-item:nth-child(3) > b")).click();
    driver.findElement(By.id("x1")).click();
    driver.findElement(By.id("x1")).sendKeys("guest2@gmail.com");
    driver.findElement(By.id("x2")).click();
    driver.findElement(By.id("x2")).sendKeys("guest2");
    driver.findElement(By.cssSelector(".col-xl-2")).click();
    driver.findElement(By.name("b1")).click();
    driver.findElement(By.linkText("SUV")).click();
    driver.findElement(By.cssSelector(".col-xxl-3:nth-child(2) img")).click();
    driver.findElement(By.linkText("Aggiungi al Carrello")).click();
    driver.findElement(By.cssSelector(".ws > b")).click();
    driver.findElement(By.name("Address")).click();
    driver.findElement(By.name("Address")).sendKeys("Via Delle Fontanelle, 9");
    driver.findElement(By.name("City")).sendKeys("Manocalzati");
    driver.findElement(By.name("State")).sendKeys("AV");
    driver.findElement(By.name("Country")).sendKeys("Italia");
    driver.findElement(By.name("Pincode")).sendKeys("83030");
    driver.findElement(By.cssSelector(".col-xl-2 > center")).click();
    driver.findElement(By.name("cash")).click();
    driver.findElement(By.cssSelector("b > input")).click();
  }
}
